## Minimum Working Example: Conjugate Calculations

In [1]:
import conjugate_map.conj_calc as conj
import datetime as dt
import pandas as pd

Load IGRF coefficients ...

### Compute conjugate points for one point:

In [2]:
ut = dt.datetime(1980, 11, 3, 18, 0, 0)
lat, lon = [-88, 0]

print("Geopack: ")
print(conj.findconj(lat, lon, ut, method="geopack"))
print("AACGM: ")
print(conj.findconj(lat, lon, ut, method="aacgm"))
print("Apex: ")
print(conj.findconj(lat, lon, ut, method="apex"))
print("Quasi-dipole: ")
print(conj.findconj(lat, lon, ut, method="qdip"))
print("\nAutomatic: ")
print(conj.findconj(lat, lon, ut, method="auto"))

Geopack:
(64.49431381410989, 298.24582917033536)
AACGM:
(63.10539805333622, -62.838832111320556)
Apex:
Method is not listed.
(0, 0)
Quasi-dipole:
Method is not listed.
(0, 0)

Automatic:
(63.10539805333622, -62.838832111320556)

In [3]:
conj.findconj(lat, lon, ut, method="auto")

(63.10539805333622, -62.838832111320556)

## Compute conjugate points for all points in a dataframe:

First we declare a dataframe:

In [4]:
df = pd.DataFrame({'Name':['McMurdo', 'SPA', 'PGC', 'SSI'], 
                   'lat': [-77.846323, -90, 44.984308, 40.019511], 
                   'lon': [ 166.668235, 0, -93.182207, -105.240014]
                  })


df

      Name        lat         lon
0  McMurdo -77.846323  166.668235
1      SPA -90.000000    0.000000
2      PGC  44.984308  -93.182207
3      SSI  40.019511 -105.240014

...and then we compute the conjugate points:

In [5]:
conj.conjcalc(df, latname = 'lat', lonname = 'lon')

      Name        lat         lon Hemisphere       PLAT        PLON
0  McMurdo -77.846323  166.668235          S  72.908386  -97.202708
1      SPA -90.000000    0.000000          S  68.071251  -66.255914
2      PGC  44.984308  -93.182207          N  44.984308  -93.182207
3      SSI  40.019511 -105.240014          N  40.019511 -105.240014

The default values are documented in the function:

In [8]:
help(conj.conjcalc)

Help on function conjcalc in module conjugate_map.conj_calc:

conjcalc(gdf, latname='GLAT', lonname='GLON', dtime=datetime.datetime(2024, 10, 8, 2, 30, 58, 456004, tzinfo=datetime.timezone.utc), is_verbose=False, method='aacgm', mode='S2N', is_saved=False, directory='output/', name='stations')
    Calculate the geographic latitudes and longitudes of conjugate points
        for all points in a dataframe. Calls findconj().

    Parameters
    ----------
    lat         : float
            Geographic latitude of station.
    lon         : float
            Geographic longitude of station.
    ut          : datetime
            Datetime used in conversion.
    is_verbose  : boolean
            If set to True, prints debugging text
    method      : string
            Defines method used in conversion. Options are 'auto', 'geopack',
            which uses IGRF + T89 to run field line traces,
            or 'aacgm', which uses AACGM v2.
    limit       : float
            Latitude limit, in degrees, used to switch between
            methods in auto mode. Default: 60.
            AACGM will converge above 35 degrees, but may be
            erroneous. See www.doi.org/10.1002/2014JA020264
            gdf         : dataframe of points whose conjugate points we're finding
    latname     : string
            Name of column containing latitude coordinates.
    lonname     : string
            Name of column containing longitude coordinates.
    dtime       : datetime
            Datetime used in conversion.
    is_verbose  : boolean
            If set to True/1, prints debugging text
    method      : string
            Method used in conversion, passed to findconj().
            Options are 'geopack', which uses IGRF + T89 to run
            field line traces, or 'aacgm'.
    mode        : string
                    'S2N'     :
                                Return station coordinates for
                                northern hemisphere, conjugate
                                for southern. Map appears over
                                the Arctic. Default.
                    'N2S'     :
                                Return station coordinates for
                                southern hemisphere, conjugate
                                for northern. Map appears over
                                the Antarctic.
                    'flip'    :
                                Return conjugate coordinates for
                                points regardless of hemisphere.
    is_saved    : boolean
        Boolean dictating whether the final .csv is saved to
        the output directory.
    directory   : string
        Name of local directory to which .csv is saved;
        'output/' by default.
    name        : string
        First part of saved filename. 'stations' by default.

    Returns
    -------
    gdf         : pandas.DataFrame
        Dataframe with PLAT, PLON columns added indicating which
        points to plot

    See Also
    --------
    conjugate_map.findconj

    Note
    ----
    Calls findconj for each entry in the dataframe.